using start-stop-daemon

diff --git a/bin/init/giraffe-agent b/bin/init/giraffe-agent
--- a/bin/init/giraffe-agent
+++ b/bin/init/giraffe-agent
@@ -21,7 +21,8 @@ PIDFILE=/var/run/giraffe/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 GIRAFFE_HOME=/opt/giraffe
 GIRAFFE_BIN=$GIRAFFE_HOME/bin/start_agent.sh
-LOG=/var/log/giraffe/$NAME.log
+GIRAFFE_LOG=/var/log/giraffe/$NAME.log
+USER="giraffe"
 VERSION=0.1
 
 # Exit if the package is not installed
@@ -43,19 +44,26 @@ VERSION=0.1
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
 
-    if [ -f $PIDFILE ]; then
-        echo "$NAME already running."
-        return 1
-    fi
-    .$GIRAFFE_BIN > $LOG 2>&1 &
-    PID=$! #`pgrep -f $GIRAFFE_BIN`
-    echo "$PID" > $PIDFILE
-    return 0
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile $PIDFILE \
+    	        --user $USER --group $GROUP \
+                -b --make-pidfile \
+                --chuid $USER \
+                --exec GIRAFFE_BIN --test > $LOG \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE \
+           	    --user $USER --group $GROUP \
+                -b --make-pidfile
+                --chuid $USER \
+                --exec GIRAFFE_BIN \
+    	|| return 2
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
 }
 
 #
@@ -63,21 +71,25 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-
-    if [ ! -f $PIDFILE ]; then
-        echo "$NAME not running."
-        exit 1
-    fi
-    PID=`cat $PIDFILE`
-    kill $PID
-	rm -f $PIDFILE
-	return 0
-
+    # Return
+ 	#   0 if daemon has been stopped
+ 	#   1 if daemon was already stopped
+ 	#   2 if daemon could not be stopped
+ 	#   other if a failure occurred
+ 	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+ 	RETVAL="$?"
+ 	[ "$RETVAL" = 2 ] && return 2
+ 	# Wait for children to finish too if this is a daemon that forks
+ 	# and if the daemon is only ever run from this initscript.
+ 	# If the above conditions are not satisfied then add some other code
+ 	# that waits for the process to drop all resources that could be
+ 	# needed by services started subsequently.  A last resort is to
+ 	# sleep for some time.
+ 	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+ 	[ "$?" = 2 ] && return 2
+ 	# Many daemons don't delete their pidfiles when they exit.
+ 	rm -f $PIDFILE
+ 	return "$RETVAL"
 }
 
 #
